// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonIcon: typeof import('./src/components/ButtonIcon.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LiAudio: typeof import('./src/components/layouts/LiAudio.vue')['default']
    LiCurrentPlay: typeof import('./src/components/layouts/LiCurrentPlay.vue')['default']
    LiFooter: typeof import('./src/components/layouts/LiFooter.vue')['default']
    LiHeader: typeof import('./src/components/layouts/LiHeader.vue')['default']
    LiHeaderNav: typeof import('./src/components/layouts/LiHeaderNav.vue')['default']
    LiIcon: typeof import('./src/components/layouts/LiIcon.vue')['default']
    LiLoginLogo: typeof import('./src/components/layouts/LiLoginLogo.vue')['default']
    LiNav: typeof import('./src/components/layouts/LiNav.vue')['default']
    LiPlayBar: typeof import('./src/components/layouts/LiPlayBar.vue')['default']
    LiScrollTop: typeof import('./src/components/layouts/LiScrollTop.vue')['default']
    PlayList: typeof import('./src/components/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
